name = "codex"
compatibility_date = "2025-03-30"
main = "worker.ts"

# Development settings
[vars]
ENVIRONMENT = "development"
JWT_SECRET = "local-development-secret-key-do-not-use-in-production"
RESEND_API_KEY = ""  # Replace with your Resend API key in your local wrangler.toml
# Google OAuth configuration (replace with your own credentials)
GOOGLE_CLIENT_ID = "your-google-client-id"
GOOGLE_CLIENT_SECRET = "your-google-client-secret"

# D1 Database configuration
[[d1_databases]]
binding = "DB"
database_name = "codex-dev-db"
database_id = "placeholder-database-id"
preview_database_id = "codex-dev-db" # Used for local development

# R2 Bucket configuration
[[r2_buckets]]
binding = "CONTENT_STORE"
bucket_name = "codex-dev-bucket"

# Production environment 
[env.production]
vars = { ENVIRONMENT = "production" }

# Production database
[[env.production.d1_databases]]
binding = "DB"
database_name = "codex-prod-db" 
database_id = "placeholder-production-database-id"

# Production storage bucket
[[env.production.r2_buckets]]
binding = "CONTENT_STORE"
bucket_name = "codex-prod-bucket"

# Scheduled tasks
[triggers]
# Process user deletion daily at midnight UTC
crons = ["0 0 * * *"]

# Local dev settings
[dev]
port = 8787
local_protocol = "http"
ip = "localhost"